fail_fast: true
repos:
    - repo: https://github.com/golangci/golangci-lint
      rev: master
      hooks:
          - id: golangci-lint
            args:
                - "--fix"
                - "--config=.golangci.yml"
