name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - name: Test
        run: make test
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage
          path: coverage.out
          retention-days: 3
  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - name: Build
        run: make build
